# Nom du workflow (visible dans l'onglet Actions)
name: GitHub Metrics

# Quand exécuter ce workflow
on:
  # Exécuter chaque jour à minuit UTC
  schedule:
    - cron: '0 0 * * *' # Exécute à 00:00 UTC tous les jours
  # Permet de déclencher le workflow manuellement
  workflow_dispatch:

# Les différentes tâches (jobs) du workflow
jobs:
  github-metrics:
    runs-on: ubuntu-latest # Environnement d'exécution

    permissions:
      contents: write # Permet au workflow d'écrire dans le dépôt (pour sauvegarder les images)

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - uses: actions/checkout@v4

      # Étape 2 : Générer les métriques
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest # Utilise la dernière version de l'action metrics
        with:
          token: ${{ secrets.GH_TOKEN }} # Utilise le PAT stocké en secret
          user: rip-alex # Votre nom d'utilisateur GitHub
          template: classic # Un template de base
          base: header, activity, community, repositories, metadata # Types de données à inclure
          config_timezone: Europe/Paris # Fuseau horaire pour les statistiques
          # Pour les contributions privées, metrics les inclura automatiquement si le PAT a les permissions
          # Les options suivantes sont des exemples pour ce que vous aviez avec github-readme-stats
          plugin_isocalendar: yes # Calendrier de contributions
          plugin_isocalendar_duration: full # Durée complète du calendrier
          plugin_languages: yes # Statistiques sur les langages
          plugin_languages_sections: most-used, recently-used # Sections des langages
          plugin_languages_limit: 8 # Nombre de langages affichés
          plugin_languages_recent_days: 14 # Langages utilisés récemment
          plugin_languages_threshold: 0% # Seuil minimum d'utilisation d'un langage
          # Pour afficher toutes les activités, y compris privées
          plugin_activity: yes
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all # Très important pour les activités privées
